dist: xenial

services:
  - docker

before_script:
  - sudo sed -i '/^127.0.0.1/ s/$/ test.localhost/' /etc/hosts

script:
  - docker-compose up -d
  - docker-compose -f tests/docker-compose.yml up -d
  - curl --fail http://test.localhost
