name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Update Hosts file
        run: sudo sed -i '/^127.0.0.1/ s/$/ test.localhost/' /etc/hosts
      - run: docker-compose up -d
      - run: docker-compose -f tests/docker-compose.yml up -d
      - run: sleep 1
      - run: curl --fail --output test.html http://test.localhost
      - run: grep 'Hello world!' test.html
